<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_classFrame</name>
   <tag></tag>
   <elementGuidId>8067421c-e81f-4951-8a1c-b83d9dca5f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='classFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;classFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b84fc760-4d88-4dda-a52d-9cf234515028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-summary.html</value>
      <webElementGuid>55028cd4-7589-4bc5-8f57-4f302c8d1ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>1a8ed778-2d15-4483-bacc-608f8fa491f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Package, class and interface descriptions</value>
      <webElementGuid>54007b64-b5d9-4f58-a51c-cd13b546ffbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightIframe</value>
      <webElementGuid>21183175-050b-4a57-970f-9ca5f416a66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;rightContainer&quot;]/iframe[@class=&quot;rightIframe&quot;]</value>
      <webElementGuid>efb138b4-1be6-4148-a3ee-0b409635cad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='classFrame']</value>
      <webElementGuid>45b0c530-2a5c-4522-929f-48027ebe8af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>9744efcf-761f-4ebb-8d29-554f8a1c908b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-summary.html' and @name = 'classFrame' and @title = 'Package, class and interface descriptions']</value>
      <webElementGuid>a466136e-7810-46f4-bb23-3f7f16836c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
