<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageListFrame</name>
   <tag></tag>
   <elementGuidId>82d5eb52-3f33-4796-97a7-860129092bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageListFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageListFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>22d1f5a1-8df2-4888-9ddd-0aa15a179218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-frame.html</value>
      <webElementGuid>c724fbb7-084d-4709-aa0f-76e776e9006e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageListFrame</value>
      <webElementGuid>7780e406-c1af-4aab-9457-d5e5783586f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Packages</value>
      <webElementGuid>e90b0d4a-2057-458c-831d-cfe90893b3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftTop&quot;]/iframe[1]</value>
      <webElementGuid>5cdad1d1-6f2a-4987-838a-38009317d5ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageListFrame']</value>
      <webElementGuid>f8d2aebd-c673-428f-9646-08b4d9412ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4a721db4-d9a0-4d3d-b588-c1435a73fbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-frame.html' and @name = 'packageListFrame' and @title = 'All Packages']</value>
      <webElementGuid>3591e914-e478-4c23-ac59-a0e98bbf5c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
