<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_html iframe</name>
   <tag></tag>
   <elementGuidId>6b1e4f45-cfa5-4de6-8fdd-92bf9ff8a891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='answer_box1_holder']/ul[6]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a860c622-f3ab-4534-bfce-270a4c1ee9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/code-examples/html/html+iframe</value>
      <webElementGuid>f9ab24b4-5499-4101-a64b-4d038a643e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>html iframe</value>
      <webElementGuid>e840b938-8a83-41b8-a5c6-86bc15c8ec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;answer_box1_holder&quot;)/ul[@class=&quot;one-third&quot;]/li[1]/a[1]</value>
      <webElementGuid>df5b254a-a52e-4fe9-9eee-a29c0e71f059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='answer_box1_holder']/ul[6]/li/a</value>
      <webElementGuid>136d49f7-735a-4187-b28f-f4dd8945afc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'html iframe')])[98]</value>
      <webElementGuid>42e4c1c4-93df-48b4-86c0-11469d9af351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iframe custom area html'])[1]/following::a[1]</value>
      <webElementGuid>b4120ace-3124-4160-b184-68f2b557e792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iframe css name'])[1]/following::a[2]</value>
      <webElementGuid>3703b46c-8127-475a-a5fd-6b0291b52aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iframe tag'])[1]/preceding::a[1]</value>
      <webElementGuid>a821a06e-0bcb-4479-9035-2775dfb5e3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iframe attributes'])[2]/preceding::a[2]</value>
      <webElementGuid>eac500fc-cabb-49d8-9923-ebeb8612070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='html iframe']/parent::*</value>
      <webElementGuid>f03d4e56-3375-4053-8afe-eabe59093534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/code-examples/html/html+iframe')])[67]</value>
      <webElementGuid>020c951b-bb18-4260-bf8f-ffffa90f8f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul[6]/li/a</value>
      <webElementGuid>ab5b1caa-193a-4bc6-92ac-259567bc4f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/code-examples/html/html+iframe' and (text() = 'html iframe' or . = 'html iframe')]</value>
      <webElementGuid>c3d785b6-35df-49e1-894a-2f1dcca45d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
